---
- name: Register variables
  set_fact:
    pyapp_app_name: "{{ pylocal_lib_name }}"
    pyapp_app_fullname: "{{ pylocal_lib_fullname }}"

- name: Ensure destination directory exists
  file: >
    path="{{ pyapp_dest_dir }}"
    state=directory

- name: Recreate the current app symlink
  file: >
    src="{{ pyapp_dest_archive_dir }}/{{ pyapp_app_fullname }}"
    dest="{{ pyapp_dest_dir }}/{{ pyapp_app_name }}"
    state=link
    force=yes

- name: Pre-install packages
  pip: >
    chdir="{{ pyapp_dest_dir }}/{{ pyapp_app_name }}"
    name={{ item }}
    state=present
    virtualenv="{{ pyapp_dest_dir }}/{{ pyapp_app_name }}/venv"
    virtualenv_site_packages=yes
  with_items: preinstall
  when: preinstall is defined
  tags: configuration

- name: Install requirements
  pip: >
    chdir="{{ pyapp_dest_dir }}/{{ pyapp_app_name }}"
    requirements=requirements.txt
    virtualenv="{{ pyapp_dest_dir }}/{{ pyapp_app_name }}/venv"
    virtualenv_python=python3.4
